[032][BE] Creation of ClassController
JohnRoyCabezas/ps-university-ebulletin-board pull request #57
Opened 2022-10-12 09:49 UTC by NiloJr-sun

## Asana Link

https://app.asana.com/0/1203011106874563/1203087509751307/f

## Pre-requisite

- [ ] Check .env files for api and client directory
- [ ] Setup postgres environment
- [ ] Postman
- [ ] Existing registered users, starting ID:3 up to ID:7

## Commands

- [ ] in the terminal, go to the project directory and cd into api directory - `cd api`
- [ ] run `php artisan migrate`
- [ ] Open postman and paste `http://127.0.0.1:8000/api/course` to fetch the class list. PS: Set the method to **GET**
- [ ] Open postman and paste `http://127.0.0.1:8000/api/course/{id}` to fetch a specific class. PS: Set the method to **GET**
- [ ] Open postman and paste 
`http://127.0.0.1:8000/api/course?course=EE 131&department=Electrical Engineering&user_ids=3,4,5,6` to create a class. PS: Set the method to **POST**
- [ ] Open postman and paste 
`http://127.0.0.1:8000/api/course/8?course=EE 131 - Updated&department=Computer Engineering&user_ids=3,4,5` to update a class. PS: Set the method to **PUT**
- [ ] Open postman and paste `http://127.0.0.1:8000/api/department/{id}` to delete a specific class. PS: Set the method to **DELETE**
## Expected Output
 
- [ ] CRUD feature for class controller

## Screenshots

![image](https://user-images.githubusercontent.com/109492180/195308833-e2db67e8-08c8-4a56-b237-6921ba3dba97.png)
![image](https://user-images.githubusercontent.com/109492180/195308905-7e107a26-8f30-41cb-8dd4-86e603eef0fd.png)
![image](https://user-images.githubusercontent.com/109492180/195309161-0073ac5d-f4f7-406a-a201-b913a12a767b.png)
![image](https://user-images.githubusercontent.com/109492180/195309309-feb74900-2af0-4489-ba27-8cf770f80aa8.png)
![image](https://user-images.githubusercontent.com/109492180/195309735-a1a69c39-4fd8-4aea-bba0-39b3f1582d61.png)
![image](https://user-images.githubusercontent.com/109492180/195309828-c610e9cf-0671-4e3f-8b48-5c6aa8d6097b.png)
![image](https://user-images.githubusercontent.com/109492180/195309874-dfe3e1b0-e38b-4e56-bf29-19bdf705edac.png)
![image](https://user-images.githubusercontent.com/109492180/195310089-aa02c7b5-0518-4280-bd4a-18ccf5fc804e.png)

2022-10-14 09:05 UTC, ejanton-sun requested changes

2022-10-14 09:05 UTC, ejanton-sun commented on api/app/Http/Controllers/CourseController.php
> +        }
instead using foreach, you can use upsert or insert
Ref: https://laravel.com/docs/9.x/eloquent#upserts

2022-10-14 09:05 UTC, ejanton-sun commented on api/app/Http/Controllers/CourseController.php
> +
remove extra space
```suggestion
```

2022-10-14 09:05 UTC, ejanton-sun commented on api/app/Http/Controllers/CourseController.php
> +        $course->courseUsers;
use `with()` when retrieving with relationship

2022-10-14 09:05 UTC, ejanton-sun commented on api/app/Http/Controllers/CourseController.php
> +        $department_id = Department::where('department', $request['department'])->get('id')->first()->id;
you can use `->first()` 
```suggestion
        $department_id = Department::where('department', $request['department'])->first()->pluck('id)
```

2022-10-14 09:05 UTC, ejanton-sun commented on api/app/Http/Controllers/CourseController.php
> +        );
I don't think you need to update also the department Id, only the `course`

2022-10-14 09:05 UTC, ejanton-sun commented on api/app/Http/Controllers/CourseController.php
> +        }
Too much foreach, refactor this one

2022-10-18 06:44 UTC, jasonchuacodes reviewed
- [ ] need to assign an instructor before course creation

2022-10-19 02:26 UTC, merged