[045][Markup] Create markup for Threads
JohnRoyCabezas/ps-university-ebulletin-board pull request #58
Opened 2022-10-12 09:52 UTC by JohnRoyCabezas

## Asana Link

https://app.asana.com/0/1203011106874563/1203087509751326/f
https://app.asana.com/0/1203011106874563/1203087509751332/f

## Pre-requisite

- [ ] npm i

## Commands

- [ ] in the terminal, go to the project directory and cd into api directory - `cd client`
- [ ] run `npm start`

## Expected Output
 
- [ ] Markup for threads.
- [ ] Created a new js file called ThreadsOptions which will be used for the hover effect on threads.
- [ ] Added clickable icons to make open and close threads

## Screenshots
Student view:
![image](https://user-images.githubusercontent.com/109579325/195311267-ff5f4fc7-ad22-4490-ab36-e46877583dee.png)

Admin View:
![image](https://user-images.githubusercontent.com/109579325/195311425-acc47ee0-8973-4743-a5bf-299aafeb20fd.png)

2022-10-14 09:09 UTC, ejanton-sun requested changes

2022-10-14 09:09 UTC, ejanton-sun commented on client/src/components/AdminMessageOptions.js
> +            message={"Are you sure you want to remove this message?"}
No need to wrap `{}` since it is not a dynamic data
```suggestion
            message="Are you sure you want to remove this message?"
```

2022-10-14 09:09 UTC, ejanton-sun commented on client/src/components/AdminMessageOptions.js
> +            buttonConfirmText={"Yes"}
No need to wrap {} since it is not a dynamic data

2022-10-14 09:09 UTC, ejanton-sun commented on client/src/components/AdminMessageOptions.js
> +            buttonCancelText={"No"}
No need to wrap {} since it is not a dynamic data

2022-10-17 08:47 UTC, jasonchuacodes commented on client/src/components/Thread.js
> +            )}
You can shorten this by using the `&&` operator and setting condition to "admin" instead.
```
{props.UserRole === "admin" && 
<RichTextEditor 
  handleRefresh={() => handleRefresh()} 
  params={params}
/>
```

2022-10-17 08:55 UTC, jasonchuacodes commented on client/src/components/Thread.js
> +  }, []);
Remove. ThreadPage is based on the set of CommentThreads for an announcement.
Create a dummy Threads object here instead and assign to an announcement.

2022-10-20 09:25 UTC, merged